services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-verysecurepassword}
      POSTGRES_DB: ${POSTGRES_DB:-card_game_app} # default DB to build when container starts
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432" # host's port: container's port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379" # host's port: container's port
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-daphne-django:
    build: ./backend
    restart: unless-stopped
    ports:
      - "${BACKEND_HOST_PORT:-8000}:8000" # host's port: container's port
    env_file:
      - .env
    environment:
      SERVICE_LABEL: ${DAPHNE_DJANGO_SERVICE_LABEL:-daphne_django}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:  # development only (for hot reloading)
      - ./backend:/app # 'bind mount' syncs changes from host to container

  backend-dramatiq-worker:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVICE_LABEL: ${DRAMATIQ_WORKER_SERVICE_LABEL:-dramatiq_worker}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes: # development only (for hot reloading)
      - ./backend:/app # 'bind mount' syncs changes from host to container

volumes:
  postgres_data:
